.TH CLIENT 1 "21 Sep 2025" "v0.4.1" "Client Program"
.SH NAME
client \- E-commerce Client Application
.SH SYNOPSIS
client [OPTIONS]
.SH DESCRIPTION
This is the main executable of the project. It demonstrates the functionality of
the static and dynamic libraries (libmyutils.a / libmyutils.so).
It provides hello functions and file utilities.
.SH OPTIONS
.TP
-h, --help
Display this help message.
.TP
-v, --version
Show program version.
.SH AUTHOR
Amara Tariq <your_email@example.com>
